"""0002_messages_status

Revision ID: 3cc1f6c84311
Revises: fd7005fcca4f
Create Date: 2026-05-12 07:40:13.602878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc1f6c84311'
down_revision: Union[str, Sequence[str], None] = 'fd7005fcca4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('status', sa.String(length=20), server_default='completed', nullable=False))
    op.add_column('messages', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'error_message')
    op.drop_column('messages', 'status')
    # ### end Alembic commands ###
